name: disqord
on:
  issues:
    types: [labeled]
           
jobs:
  send-to-discord:
    if: contains(github.event.issue.labels.*.name, 'bug')
    name: "Send To Discord"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "hugoalh/GitHubAction.SendToDiscord@v2.0.0"
        with:
          webhook_id: '803554374882033675'
          webhook_token: 'K4Wfv6fFoH5tOu9dGn_DlrjJ4ETIBnkn1k4GPiK7xq5O-pCuMfP6DU42O8pdj4nE7Bhe'
          variable_join: "."
          # variable_list_external:
          variable_prefix: "%"
          variable_suffix: "%"
          webhook_name: 'QC team'
          webhook_avatarurl: 'https://i.imgur.com/hxp6wC7.png'
          message_embed_title: ${{ github.event.issue.title }}
          message_embed_description: ${{ github.event.issue.body }}
          message_embed_titleurl: ${{ github.event.issue.html_url }}
          message_embed_colour: "255,0,0"
          message_embed_authorname: ${{ github.event.issue.user.login }}
          message_embed_authorurl: ${{ github.event.issue.user.html_url }}
          message_embed_authoravatarurl: ${{ github.event.issue.user.avatar_url }}
          message_usetexttospeech: "false"
