name: disqord
on:
  issues:
    types: [labeled]
jobs:
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          username: QC team
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.WEBHOOK_URL }}
          content: "test content"
