name: disqord
on:
  issues:
    types: [opened, edited, milestoned]
jobs:
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: binotaliu/action-discord-notifier@v1
        with:
          message-title: New Commits Pushed
          webhook: https://discord.com/api/webhooks/803554374882033675/K4Wfv6fFoH5tOu9dGn_DlrjJ4ETIBnkn1k4GPiK7xq5O-pCuMfP6DU42O8pdj4nE7Bhe
