name: disqord
on:
  issues:
    types: [labeled]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v2.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          raw-data: '{"event": "deployment", "repository": "joelwmale/webhook-action"}'
        
